#!/usr/bin/with-contenv bash
set -x
PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" papercut
usermod -o -u "$PUID" papercut

mkdir -p /config/data
for i in data/conf custom logs data/backups; do
    if [ ! -d /config/${i} ]; then
        cp -R /defaults/${i} /config/${i}
        ln -s /config/${i} /papercut/server/${i}
    fi
done

# permissions
chown -R abc:abc \
    /config
