#!/usr/bin/with-contenv bash

mkdir -p /config/data
for i in data/conf custom logs data/backups; do
    if [ ! -d /config/${i} ]; then
        cp -R /defaults/${i} /config/${i}
        ln -s /config/${i} /papercut/server/${i}
    fi
done

# permissions
chown -R abc:abc \
    /config
/papercut/server/bin/linux-x64/setperms
