#!/usr/bin/with-contenv bash
set -x
userdel abc &>/dev/null # hacky way to keep uid/gid for papercut user

PUID=${PUID:-911}
PGID=${PGID:-911}

export HOME=/tmp # usermod takes forever as it changes permissions
groupmod -o -g "$PGID" papercut
usermod -o -u "$PUID" papercut
export HOME=/papercut

mkdir -p /config/data
for i in data/conf custom logs data/backups; do
    if [ ! -d /config/${i} ]; then
        cp -R /defaults/${i} /config/${i}
        ln -s /config/${i} /papercut/server/${i}
    fi
done

# permissions
chown -R papercut:papercut \
    /config \
    /papercut
/papercut/server/bin/linux-x64/setperms
